### PR TITLE
new branch deleted some code

### PR DESCRIPTION
**Pull request by elzarosmonalieva**
I have deleted some code and added a new one

### CODE REVIEW

**Comment by kanykej** [comment]
good job

**Review by elzarosmonalieva — COMMENTED** [review]
good job

**Review by kanykej — APPROVED** [review]
seems good

**Comment by zafar2826138** [comment]
looks good

**Comment by zafar2826138** [comment]
good

**Comment by kanykej** [comment]
seems good

**Review by kanykej — COMMENTED** [review]
good

**Pull request closed without merging**
